[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
categories = ["api-bindings", "web-programming"]
description = "An abstraction for Matrix API endpoints."
documentation = "https://docs.rs/ruma-api"
homepage = "https://github.com/ruma/ruma-api"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-api"
readme = "README.md"
repository = "https://github.com/ruma/ruma-api"
version = "0.10.0"
edition = "2018"

[dependencies]
http = "0.1.18"
serde_json = "1.0.40"
serde_urlencoded = "0.6.1"
ruma-identifiers = "0.14.0"

percent-encoding = { version = "2.0.0", optional = true }
ruma-api-macros = { path = "ruma-api-macros", optional = true }
serde = { version = "1.0.98", features = ["derive"], optional = true }
url = { version = "2.0.0", optional = true }

[features]
default = ["with-ruma-api-macros"]
with-ruma-api-macros = ["percent-encoding", "ruma-api-macros", "serde", "url"]

[workspace]
members = [
  "ruma-api-macros",
]
