cargo-features = ["public-dependency"]

[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
categories = ["api-bindings", "web-programming"]
description = "A procedural macro for generating ruma-api Endpoints."
documentation = "https://docs.rs/ruma-api-macros"
homepage = "https://github.com/ruma/ruma-api"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-api-macros"
readme = "README.md"
repository = "https://github.com/ruma/ruma-api"
version = "0.7.1"
edition = "2018"

[dependencies]
quote = "0.6.13"
proc-macro2 = "0.4.30"

[dependencies.syn]
version = "0.15.42"
features = ["full"]

[lib]
proc-macro = true
